# Site settings
title: InBig
email: inbig2019@naver.com
description: > # this means to ignore newlines until "baseurl:"
  "InBig" : 인하대학교 빅데이터 동아리, 인빅입니다.
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://inbig.github.io # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
google_analytics: UA-175052880-1
disqus: 'demowebsite'
# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate # 플러그인 사용을 의미한다.(Jekyll 3)
# pagination settings
paginate: 8 # 한 페이지당 보여줄 posts 수
# :num은 페이지마다 번호를 각각 부여한다.
paginate_path: "/posts/page/:num" # 다음 페이지에 해당하는 URL
